language: java
jdk:
- oraclejdk8
- openjdk8
before_script:
- chmod a+x gradlew
script: "./gradlew exec"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GH_TOKEN
  file: build/libs/transcript_tether-*.jar
  file_glob: true
  on:
    repo: GCRC/transcript_tether
    tags: true
    jdk: openjdk8
